### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by rahlk** [Lost-In-MASE/x9115AAP#1]
In [Line 34](https://github.com/Lost-In-MASE/x9115AAP/blob/master/hw/code/4/Schaffer.py#L34), your min/max bounds are -100 and +100, please change that to -10^5 to 10^5

**Comment by aadisriram** [comment]
The reason I reduced this was to achieve convergence, I shall change and give it another try.

**Comment by rahlk** [comment]
I see. Here are some things you can do to converge:
- Increase number of iterations. Set it to, say, 10^6.
- Change your neighborhood function, use current value of x to obtain it neighbor, instead of randomly picking from the entire range.

**Comment by aadisriram** [comment]
Thanks for the tip, I'll try that out

**Comment by aadisriram** [comment]
I changed the bounds and updated the output.
